name: CI/CD Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    name: Run All Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install pytest pytest-cov pytest-mock

    - name: Run all tests
      run: |
        python -m pytest -v --cov=src --cov-report=xml

    - name: Upload coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage
        path: coverage.xml

  test-categories:
    name: Test Categories
    runs-on: ubuntu-latest
    needs: test
    strategy:
      matrix:
        category: ['login', 'cadastros', 'pagamentos', 'pedidos', 'catalogo']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install pytest pytest-cov pytest-mock

    - name: Run ${{ matrix.category }} tests
      run: |
        # Use arquivos específicos em vez de marcas
        python -m pytest tests/test_${{ matrix.category }}.py -v --cov=src --cov-report=xml

    - name: Upload ${{ matrix.category }} coverage
      uses: actions/upload-artifact@v4
      with:
        name: coverage-${{ matrix.category }}
        path: coverage.xml
